### ISSUE TITLE
Pandas: SettingWithCopyWarning

### ISSUE THREAD

**Issue by abaumg** [abaumg/covid19-bz-scraper#7]
When I run `process_municipalities_singleday.py` on my computer, I get the following warning:

```
(venv) andreas@omena:~/covid19-bz-scraper$ python process_municipalities_singleday.py 
/home/andreas/covid19-bz-scraper/venv/lib/python3.6/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s
process_municipalities_singleday.py:63: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_totale['datum'] = date
```

The data file `/data/covid19_bz_municipalities.csv` is updated nevertheless. Can I safely ignore the warning?

**Comment by tyrasd** [comment]
yeah, these can be ignored since in this case the writing to a copy of a dataframe is actually the expected result. Pandas apparently warns in such situations because a very similar (for pandas indistinguishable) situation can occur when trying to set values of a dataframe as a "chained assignment", which can be confusing for new users. See https://stackoverflow.com/a/20627316/1627467 for more info. I will disable this type of warning for this script.
