### ISSUE TITLE
Automatic update

### ISSUE THREAD

**Issue by abaumg** [abaumg/covid19-bz-scraper#8]
It would be nice to have automatic updates for the data files. This could be achieved by a cronjob (shell or python script), but I'm not sure what would be the best way to commit the changes by a script. Any suggestions?

**Comment by tyrasd** [comment]
Well, if you configure a git client on the server (incl. creating of a dedicated ssh key), it can execute `git add data/*; git commit -m "daily data update by bot"; git pull --rebase; git push` after doing the "daily" update. It would probably make sense to create a dedicated github "user" account for this, so that it is clear which commits come from the bot :wink: 

Do you have an ide how to scrape the links of the press releases and of the municipalities spreadsheets in an automated way? And at what time one would run the daily updates, since the press releases are not always published at the same time. :thinking: In order to run relatively stable, the script would also need to have some fail-saves included, e.g. to avoid committing the same data twice, etc.

**Comment by abaumg** [comment]
I implemented the checks to avoid duplicate data for scrape_pressreleases.py in 4743680, for scrape_graphics.py in cbebc3a and for process_municipalities_singleday.py in f597af8. Also, I implemented a update script `autoupdate_repo.py` which can be run by a cronjob on my server. Let's see how this works out.

**Comment by abaumg** [comment]
> Do you have an ide how to scrape the links of the press releases and of the municipalities spreadsheets in an automated way?

Do you need the link from the press release (e.g. `Anzahl der positiv getesteten Personen nach Gemeinden, Stand: 10. Mai 2020 (Quelle: Südtiroler Sanitätsbetrieb) [MS EXCEL 2007 56 KB]`)? Can't you just use the static link https://afbs.provinz.bz.it/upload/coronavirus/CoronavirusPositivi.xlsx ?

**Comment by tyrasd** [comment]
> Can't you just use the static link https://afbs.provinz.bz.it/upload/coronavirus/CoronavirusPositivi.xlsx ?

I think this one would work fine. :+1:

**Comment by abaumg** [comment]
Hmm, I need better checks for `process_municipalities_singleday.py` to avoid duplicate data. The other two scripts run smooth with the cronjob.

**Comment by tyrasd** [comment]
You could perhaps check whether the file [`singledatemunicST_csv`](https://github.com/abaumg/covid19-bz-scraper/blob/master/process_municipalities_singleday.py#L76) already exists and if it does abort the script?!

```python
singledatemunicST_csv = …
if os.path.exists(outdir+singledatemunicST_csv):
    print("output file already exist", file=sys.stderr)
    sys.exit(1)
```

**Comment by tyrasd** [comment]
@abaumg ping. do you think one of the solutions will work for the municipalities data, or should I continue to do it manually?

**Comment by abaumg** [comment]
@tyrasd You're right, my check was bullshit. I only checked the existence of today's data, but not yesterday's data. The XLS is published unfrequently. Your fix is generic and thus better.
